/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElEpMale: typeof import('element-plus/es')['ElEpMale']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconEpAim: typeof import('~icons/ep/aim')['default']
    IconEpEdit: typeof import('~icons/ep/edit')['default']
    IconEpLoading: typeof import('~icons/ep/loading')['default']
    IconEpMale: typeof import('~icons/ep/male')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpChatDotRound: typeof import('~icons/ep/chat-dot-round')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpShare: typeof import('~icons/ep/share')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
